### ISSUE TITLE
set current item fixed to 1

### ISSUE THREAD

**Issue by ticofab** [TobiasBuchholz/CircularViewPager#6]
Hi, and thanks for this library. I can't get setCurrentItem to work properly - the item I set is always off by one. The only way seems to be to use a "+1" when I invoke setCurrentItem, so for instance: if the user clicks on the item 0, I need to launch the pager and use setCurrentPager(1).
Is this somehow expected by the CircularViewPager? I see that in the CircularViewPagerHandler constructor, the current item is set at 1 by default and not at 0.
Thanks for any hint.

**Comment by TobiasBuchholz** [comment]
Yep, this behaviour is intended, otherwise it wouldn't be possible to swipe to the left. But you've got a point, the BaseCircularViewPagerAdapter should be changed in the way that it overrides setCurrentItem() and applies +1 itself, so it works like a usual adapter.

**Comment by afiqiqmal** [comment]
same goes to me..i had to +1.. only onpageselected return exact position
